---
# handlers file for docker
- name: Restart Docker services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    daemon_reload: true
    enabled: true
    state: "restarted"
  listen:
    - "restart docker"
  loop: "{{ _docker_services }}"
...
