---
# handlers file for docker
- name: Restart Docker services
  ansible.builtin.systemd_service:
    name: "{{ docker_service_name }}"
    daemon_reload: true
    enabled: true
    state: "restarted"
  listen:
    - "restart docker"
...
