---
# handlers file for airline_manager
- name: Restart Airline Manager
  ansible.builtin.systemd_service:
    name: "{{ airline_manager_service_name }}"
    daemon_reload: true
    enabled: true
    state: restarted
  listen:
    - "restart airline_manager"
...
